classDiagram

    class DIMobileSDK
    DIMobileSDK : +enrollUserDevice(PrivateKey userDevicePrvKey, String idToken)
    DIMobileSDK : +endorseUserOrgPersonas(PrivateKey userDevicePrvKey, String idToken)
